import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import '@fortawesome/fontawesome-free/css/all.min.css';
import AuthProvider from "../lib/context/AuthContext";
import ReduxProvider from "../lib/Redux/ReduxProvider/ReduxProvider";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  style: ["normal", "italic"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// eslint-disable-next-line @typescript-eslint/no-empty-object-type
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
    
        <ReduxProvider>
          <AuthProvider>
            {children}
            </AuthProvider>
        </ReduxProvider>
        
      </body>
    </html>
  );
}
