import type { Metadata } from "next";
import { Inter } from 'next/font/google';
import "./globals.css";
import '@fortawesome/fontawesome-free/css/all.min.css'
import Navbar from "../Components/Navbar";

const inter = Inter({
  subsets: ['latin'], 
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  style: ['normal', 'italic'], 
  display: 'swap', 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={inter.className}
      >
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
