import type { Metadata } from "next";
import { Inter } from 'next/font/google';
import { Poppins } from 'next/font/google';
import "./globals.css";
import '@fortawesome/fontawesome-free/css/all.min.css'
import AuthProvider from "../context/AuthContext";


const inter = Inter({
  subsets: ['latin'], 
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  style: ['normal', 'italic'], 
  display: 'swap', 
});

const poppins = Poppins({
  subsets: ['latin'], 
  weight: ['400', '500', '600', '700'], 
  style: ['normal', 'italic'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={`${poppins.className}`}>

        <AuthProvider> 
          {children}
        </AuthProvider>
        
      </body>
    </html>
  );
}
